name: build-image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: build docker image
        run: |
          docker build . -t $REPOSITORY/$IMAGE_NAME:v`date +%Y%m%d` -t $REPOSITORY/$IMAGE_NAME:latest
      - name: push image to dockerhub
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push $REPOSITORY/$IMAGE_NAME:v`date +%Y%m%d`
          docker push $REPOSITORY/$IMAGE_NAME:latest
        env:
          REPOSITORY: colachen
          IMAGE_NAME: tftp-hpa
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
