name: build-image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Define variables
        run: |
          echo "colachen" > REPOSITORY
          echo "tftp-hpa" > IMAGE_NAME

      - name: build docker image
        run: |
          docker build . -t $(cat REPOSITORY)/$(cat IMAGE_NAME):v`date +%Y%m%d` -t $(cat REPOSITORY)/$(cat IMAGE_NAME):latest
      - name: push image to dockerhub
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push $(cat REPOSITORY)/$(cat IMAGE_NAME):v`date +%Y%m%d`
          docker push $(cat REPOSITORY)/$(cat IMAGE_NAME):latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
